---
title: "The Indonesian Economist"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cosmo
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Macroeconomics #1
=====================================  

Column {data-width=100}
-------------------------------------


### Macro Condition
```{r}
rate <- 77
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Banking Condition
```{r}
rate <- 47
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```



Column {data-width=200}
-------------------------------------
   
### Chart 1

```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("m2mom.csv")
fore <- read.csv("m2mom_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "M2", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "M2 (MoM)"), showlegend = FALSE)
  
p
```
 
### Chart 3
    
```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("Kurs.csv")
fore <- read.csv("kurs_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "Exchange Rate (IDR/USD)", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "IDR/USD"), showlegend = FALSE)
  
p
```

Column {data-width=200}
-------------------------------------
   
### Chart 2

```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("inflasimom.csv")
fore <- read.csv("inflasimom_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "Inflation", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "Inflation (MoM)"), showlegend = FALSE)
  
p
``` 

### Chart 4
    
```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("ihsg.csv")
fore <- read.csv("ihsg_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "JCI", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "JCI"), showlegend = FALSE)
  
p
```


Macroeconomics #2
=====================================  

Column {data-width=100}
-------------------------------------


### Macro Condition
```{r}
rate <- 77
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Banking Condition
```{r}
rate <- 47
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```



Column {data-width=200}
-------------------------------------
   
### Chart 5

```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("ekspormom.csv")
fore <- read.csv("ekspormom_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "Exports", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "Exports (MoM)"), showlegend = FALSE)
  
p
```
 
### Chart 7
    
```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("bond10y.csv")
fore <- read.csv("bond10y_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "Bond Yields", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "Yield (10Y)"), showlegend = FALSE)
  
p
```


Column {data-width=200}
-------------------------------------
   
### Chart 6

```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("impormom.csv")
fore <- read.csv("impormom_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "Imports", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "Imports (MoM)"), showlegend = FALSE)
  
p
``` 

### Chart 8
    
```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
```


Banking
=====================================     
   
Column {data-width=100}
-------------------------------------


### Macro Condition
```{r}
rate <- 77
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Banking Condition
```{r}
rate <- 47
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```


Column {data-width=200}
-------------------------------------
   
### Chart 1

```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("kreditmom.csv")
fore <- read.csv("kreditmom_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "Loan", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "Loan Growth (MoM)"), showlegend = FALSE)
  
p
```
 
### Chart 3
    
```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("car.csv")
fore <- read.csv("car_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "CAR", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "CAR (%)"), showlegend = FALSE)
  
p
```

Column {data-width=200}
-------------------------------------
   
### Chart 2

```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("npl.csv")
fore <- read.csv("npl_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "NPL", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "NPL (%)"), showlegend = FALSE)
  
p
``` 

### Chart 4
    
```{r , fig.width=8, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
x <- read.csv("nim.csv")
fore <- read.csv("nim_fore.csv")
f1 <- list(family = "Arial, sans-serif", size = 10, color = "black")

m <- x[which.max(x$Dates), ]
a <- list(x = m$Dates, y = m$fit, text = ~paste(m$Dates, ': ', m$fit), xref = "x", yref = "y", showarrow = TRUE, arrowhead = 7, ax = 20, ay = -40)

p <- plot_ly() %>%
  add_lines(x = x$Dates, y = x$fit, type = 'scatter', mode = 'ribbons', color = I("black"), name = "observed") %>%
  add_ribbons(x = fore$Dates, ymin = fore$lwr, ymax = fore$upr, color = I("gray75"), name = "95% confidence") %>%
  add_lines(x = fore$Dates, y = fore$fit, color = I("blue"), name = "prediction") %>%
layout(annotations = a, title = "NIM", xaxis = list(dtick = 12, tickfont = f1), yaxis = list(title = "NIM (%)"), showlegend = FALSE)
  
p
```

About {data-orientation=rows}
=====================================

- __Name:__ Victor GP Matindas
- __Ocupation:__ Economist/Data Scientist
- __E-Mail:__ eye_osiris@yahoo.com 